---
- set_fact:
    greeting_application_file: /opt/engineering/greeting.py

- name: Create sudoers file for developers group
  template:
    src: templates/developers.j2
    dest: /etc/sudoers.d/developers
    validate: 'visudo -cf %s'
    owner: root
    group: root
    mode: 0440
